var name = "Hero Alan";


// Reserverd keyword not allowed; 
var false = 25; 
var delete = 'delete';

// Name should be one word 

var nayok name ="tom Cruise";

// Quote is not allowed
var 'naaaaaaaaaaaaaaaaaaayika' = 'shabnoor';

var my-office-address = "andorkilla bandorban";
var my_office_address = "andorkilla bandorban";
var myOfficeAddress =   "andorkilla bandorban";
var myofficeaddress =   "andorkilla bandorban";

// ALl Uppercase Used rarely 
var PIE = 3.14; 

var 999price = 25;
var p45 = 96;
var userHomeAddress = 'Katabon'